language: go
sudo: false

matrix:
  include:
    - go: 1.12
    - go: 1.13
    - go: 1.14
    - go: tip

install:
  - # Skip

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet .
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
